// Comprehensive categories mapping for the frontend
// This should be kept in sync with server/categories.py
export const CATEGORIES = {
  // Home Services
  landscaping: '🏡 Landscaping',
  landscaper: '🌿 Landscaper',
  lawn_care: '🪴 Lawn Care',
  gardening: '🌱 Gardening',
  plumber: '🔧 Plumber',
  plumbing: '🚿 Plumbing',
  electrician: '⚡ Electrician',
  electrical: '🔌 Electrical',
  hvac: '❄️ HVAC',
  heating_cooling: '🌡️ Heating & Cooling',
  carpenter: '🪚 Carpenter',
  carpentry: '🪵 Carpentry',
  painter: '🎨 Painter',
  painting: '🖌️ Painting',
  roofer: '🏠 Roofer',
  roofing: '🏘️ Roofing',
  locksmith: '🔐 Locksmith',
  handyman: '🔨 Handyman',
  construction: '🏗️ Construction',
  contractor: '👷 Contractor',
  flooring: '🪵 Flooring',
  tile: '🧱 Tile',
  welding: '🔥 Welding',
  welder: '⚒️ Welder',
  appliance_repair: '🔧 Appliance Repair',
  fence_contractor: '🚧 Fence Contractor',
  masonry: '🧱 Masonry',
  concrete: '🏛️ Concrete',

  // Food & Dining
  restaurant: '🍽️ Restaurant',
  cafe: '☕ Cafe',
  coffee_shop: '☕ Coffee Shop',
  fast_food: '🍔 Fast Food',
  bar: '🍺 Bar',
  pub: '🍻 Pub',
  bakery: '🥐 Bakery',
  pizza: '🍕 Pizza',
  pizzeria: '🍕 Pizzeria',
  food_truck: '🚚 Food Truck',
  catering: '🍴 Catering',
  ice_cream: '🍦 Ice Cream',
  deli: '🥪 Deli',
  butcher: '🥩 Butcher',
  seafood: '🐟 Seafood',
  food_market: '🛒 Food Market',
  brewery: '🍺 Brewery',
  winery: '🍷 Winery',

  // Healthcare
  dentist: '🦷 Dentist',
  doctor: '👨‍⚕️ Doctor',
  pharmacy: '💊 Pharmacy',
  hospital: '🏥 Hospital',
  veterinary: '🐾 Veterinary',
  optometrist: '👓 Optometrist',
  chiropractor: '🦴 Chiropractor',
  physical_therapist: '🏃 Physical Therapist',
  mental_health: '🧠 Mental Health',
  counselor: '💭 Counselor',
  therapist: '🧘 Therapist',
  nutritionist: '🥗 Nutritionist',
  dermatologist: '🧴 Dermatologist',
  orthodontist: '🦷 Orthodontist',
  pediatrician: '👶 Pediatrician',
  urgent_care: '🚨 Urgent Care',
  clinic: '🏥 Clinic',

  // Automotive
  auto_repair: '🚗 Auto Repair',
  car_dealer: '🚙 Car Dealer',
  gas_station: '⛽ Gas Station',
  car_wash: '🧼 Car Wash',
  auto_parts: '🔩 Auto Parts',

  // Personal Care
  barber: '💇 Barber',
  hairdresser: '💇‍♀️ Hairdresser',
  hair_salon: '💇‍♀️ Hair Salon',
  makeup_artist: '💄 Makeup Artist',
  makeup_studio: '💋 Makeup Studio',
  nail_salon: '💅 Nail Salon',
  nail_technician: '💅 Nail Technician',
  spa: '🧖 Spa',
  esthetician: '✨ Esthetician',
  cosmetology: '💆 Cosmetology',
  massage: '💆 Massage',
  massage_therapist: '💆‍♀️ Massage Therapist',
  tattoo: '🎨 Tattoo Studio',
  tattoo_artist: '🖋️ Tattoo Artist',
  piercing: '💎 Piercing Studio',
  brow_studio: '👁️ Brow Studio',
  lash_studio: '👁️‍🗨️ Lash Studio',
  waxing: '🪒 Waxing',
  tanning_salon: '☀️ Tanning Salon',
  barbershop: '💇 Barbershop',

  // Fitness & Recreation
  gym: '💪 Gym',
  fitness_center: '🏋️ Fitness Center',
  yoga: '🧘 Yoga Studio',
  yoga_studio: '🧘‍♀️ Yoga Studio',
  pilates: '🧘‍♂️ Pilates',
  crossfit: '🏋️‍♀️ CrossFit',
  martial_arts: '🥋 Martial Arts',
  dance_studio: '💃 Dance Studio',
  dance_school: '🕺 Dance School',
  golf_course: '⛳ Golf Course',
  golf_club: '🏌️ Golf Club',
  tennis_club: '🎾 Tennis Club',
  swimming_pool: '🏊 Swimming Pool',
  rock_climbing: '🧗 Rock Climbing',
  skating_rink: '⛸️ Skating Rink',
  bowling: '🎳 Bowling',
  arcade: '🎮 Arcade',
  mini_golf: '⛳ Mini Golf',
  sports_bar: '🏀 Sports Bar',

  // Professional Services
  lawyer: '⚖️ Lawyer',
  attorney: '⚖️ Attorney',
  legal_services: '📜 Legal Services',
  accountant: '📊 Accountant',
  accounting: '📈 Accounting',
  bookkeeping: '📒 Bookkeeping',
  real_estate: '🏘️ Real Estate',
  real_estate_agent: '🏠 Real Estate Agent',
  realtor: '🏡 Realtor',
  insurance: '🛡️ Insurance',
  insurance_agent: '🛡️ Insurance Agent',
  financial_advisor: '💰 Financial Advisor',
  financial_planning: '💵 Financial Planning',
  tax_preparation: '📋 Tax Preparation',
  consulting: '💼 Consulting',
  marketing_agency: '📢 Marketing Agency',
  advertising_agency: '📺 Advertising Agency',
  web_design: '💻 Web Design',
  graphic_design: '🎨 Graphic Design',
  photography: '📷 Photography',
  photographer: '📸 Photographer',
  videography: '🎥 Videography',
  event_planning: '🎉 Event Planning',
  wedding_planner: '💒 Wedding Planner',

  // Retail
  grocery: '🛒 Grocery Store',
  supermarket: '🏪 Supermarket',
  convenience: '🏪 Convenience Store',
  clothing: '👕 Clothing Store',
  apparel: '👔 Apparel',
  shoes: '👟 Shoes',
  shoe_store: '👢 Shoe Store',
  hardware: '🔨 Hardware Store',
  home_improvement: '🏠 Home Improvement',
  furniture: '🪑 Furniture Store',
  electronics: '📱 Electronics Store',
  bookstore: '📚 Bookstore',
  boutique: '👗 Boutique',
  department_store: '🏬 Department Store',
  discount_store: '💰 Discount Store',
  thrift_store: '♻️ Thrift Store',
  vintage_store: '👘 Vintage Store',
  antique_store: '🕰️ Antique Store',
  art_gallery: '🖼️ Art Gallery',
  craft_store: '✂️ Craft Store',
  hobby_shop: '🎨 Hobby Shop',
  toy_store: '🧸 Toy Store',
  sports_store: '⚽ Sports Store',
  outdoor_store: '🏕️ Outdoor Store',
  bike_shop: '🚲 Bike Shop',
  pawn_shop: '💎 Pawn Shop',

  // Education
  school: '🏫 School',
  elementary_school: '📚 Elementary School',
  high_school: '🎓 High School',
  university: '🎓 University',
  college: '🏛️ College',
  driving_school: '🚗 Driving School',
  language_school: '🌍 Language School',
  tutoring: '📖 Tutoring',
  tutor: '✏️ Tutor',
  music_school: '🎵 Music School',
  art_school: '🎨 Art School',
  preschool: '👶 Preschool',
  daycare: '🏫 Daycare',
  childcare: '👨‍👩‍👧 Childcare',

  // Accommodation
  hotel: '🏨 Hotel',
  motel: '🛣️ Motel',
  bed_breakfast: '🛏️ Bed & Breakfast',
  resort: '🏖️ Resort',
  hostel: '🛋️ Hostel',
  campground: '⛺ Campground',
  rv_park: '🚐 RV Park',

  // Entertainment
  movie_theater: '🎬 Movie Theater',
  cinema: '🎥 Cinema',
  theater: '🎭 Theater',
  comedy_club: '😄 Comedy Club',
  concert_hall: '🎵 Concert Hall',
  museum: '🏛️ Museum',
  zoo: '🦁 Zoo',
  aquarium: '🐠 Aquarium',
  park: '🌳 Park',
  amusement_park: '🎢 Amusement Park',
  water_park: '💦 Water Park',
  casino: '🎰 Casino',
  nightclub: '🎉 Nightclub',
  karaoke: '🎤 Karaoke',
  escape_room: '🚪 Escape Room',
  billiards: '🎱 Billiards',
  pool_hall: '🎱 Pool Hall',

  // Services
  bank: '🏦 Bank',
  credit_union: '🏦 Credit Union',
  atm: '💳 ATM',
  post_office: '📮 Post Office',
  mailing_center: '📬 Mailing Center',
  dry_cleaner: '👔 Dry Cleaner',
  laundromat: '🧺 Laundromat',
  laundry_service: '👕 Laundry Service',
  storage: '📦 Storage Facility',
  moving_company: '🚚 Moving Company',
  moving_storage: '📦 Moving & Storage',
  cleaning_service: '🧹 Cleaning Service',
  housekeeping: '🏠 Housekeeping',
  pet_grooming: '🐕 Pet Grooming',
  dog_groomer: '🐶 Dog Groomer',
  pet_sitting: '🐾 Pet Sitting',
  vet_clinic: '🏥 Vet Clinic',
  animal_hospital: '🐕 Animal Hospital',
  pet_store: '🐕 Pet Store',
  pet_supplies: '🐾 Pet Supplies',
  florist: '🌹 Florist',
  flower_shop: '🌸 Flower Shop',
  jewelry: '💍 Jewelry Store',
  jewelry_store: '💎 Jewelry Store',
  watch_repair: '⌚ Watch Repair',
  gift_shop: '🎁 Gift Shop',
  tailor: '✂️ Tailor',
  alterations: '🧵 Alterations',
  shoe_repair: '👞 Shoe Repair',
  key_shop: '🗝️ Key Shop',
  locksmith_service: '🔐 Locksmith Service',
};

